### ISSUE TITLE
Typo in README: "https://github.com/GeisignerBTI/TrustedGRUB2" should be "...inger..."

### ISSUE THREAD

**Issue by josh-zaps** [GeisingerBTI/tpm-luks#8]
Subject says it all.

**Comment by johnwallace123** [comment]
Resolved in 40448760b131eb95ba5ff7cbccc7ddccf6e276fe.  Thanks for the catch!

**Comment by josh-zaps** [comment]
Most welcome!  Thanks for the project!

**Comment by johnwallace123** [comment]
Happy to help; please let me know how it works for you or if you have any other issues getting it to work.  Always good to have more eyes on an issue.
